name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build-prod

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.${{ github.run_number }}
          name: Release v1.${{ github.run_number }}
          body: "Automated release from GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Firebase
        run: |
          echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} | base64 -d > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
          npx firebase deploy --only hosting
